apiVersion: v1
data:
  greetings: Hello from WebSphere Liberty managed by WebSphere Liberty Operator;Hello
    from the pipeline
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: greeting
  name: greeting
---
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  labels:
    app: greeting
  name: greeting
spec:
  applicationImage: quay.io/client-engineering-cee/whe/greeting-wl:ty
  createKnativeService: false
  env:
  - name: GREETINGS
    valueFrom:
      configMapKeyRef:
        key: greetings
        name: greeting
        optional: false
  expose: true
  license:
    accept: true
    edition: IBM WebSphere Application Server Liberty Core
    productEntitlementSource: IBM Cloud Pak for Applications
  manageTLS: false
  networkPolicy:
    disable: true
  probes:
    liveness:
      httpGet:
        path: /api/greetings
        port: 9080
        schema: HTTP
    readiness:
      httpGet:
        path: /api/greetings
        port: 9080
        schema: HTTP
    startup:
      httpGet:
        path: /api/greetings
        port: 9080
        schema: HTTP
  pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 128Mi
  route:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  service:
    port: 9080
